<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9516692b-5bfc-4987-961c-227dd1f85a26</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Shared\Index.cshtml" />
    <Content Remove="Views\Shared\_MainContent.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HoraCerta.Application\HoraCerta.Application.csproj" />
    <ProjectReference Include="..\HoraCerta.CrossCutting\HoraCerta.CrossCutting.csproj" />
    <ProjectReference Include="..\HoraCerta.Infrastructure\HoraCerta.Infrastructure.csproj" />
  </ItemGroup>

</Project>
